<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-08-30 22:16:28 --> Query error: Incorrect integer value: '' for column 'visitor_1_dl_number' at row 1 - Invalid query: INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`, `is_unavailable`, `id_users_provider`, `id_services`, `id_inmate`, `visitor_2_name`, `visitor_3_name`, `visitor_4_name`, `visitor_1_dl_number`, `visitor_2_dl_number`, `visitor_3_dl_number`, `visitor_4_dl_number`, `visitor_1_dl_state`, `visitor_2_dl_state`, `visitor_3_dl_state`, `visitor_4_dl_state`, `visitor_1_dl`, `visitor_2_dl`, `visitor_3_dl`, `visitor_4_dl`, `id_users_customer`, `book_datetime`, `hash`) VALUES ('2021-08-31 18:00:00', '2021-08-31 18:20:00', '', 0, '20', '3', '4', '', '', '', '', '', '', '', 'Texas', 'Select', 'Select', 'Select', 'C:\\fakepath\\image.png', '', '', '', '13', '2021-08-30 22:16:28', '32cba0951414ef6004bc828ce2841c0b')
ERROR - 2021-08-30 22:20:10 --> Query error: Field 'new_test_field' doesn't have a default value - Invalid query: INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`, `is_unavailable`, `id_users_provider`, `id_services`, `id_inmate`, `visitor_2_name`, `visitor_3_name`, `visitor_4_name`, `visitor_1_dl_number`, `visitor_2_dl_number`, `visitor_3_dl_number`, `visitor_4_dl_number`, `visitor_1_dl_state`, `visitor_2_dl_state`, `visitor_3_dl_state`, `visitor_4_dl_state`, `visitor_1_dl`, `visitor_2_dl`, `visitor_3_dl`, `visitor_4_dl`, `location`, `id_users_customer`, `book_datetime`, `hash`) VALUES ('2021-08-31 17:00:00', '2021-08-31 17:20:00', '', 0, '4', '1', '0', '', '', '', '1', '1', '1', '1', 'Texas', 'Select', 'Select', 'Select', 'C:\\fakepath\\image.png', '', '', '', 'Room 1', '13', '2021-08-30 22:20:10', 'e9dc37211f9ac959f9bde85901e86e55')
ERROR - 2021-08-30 22:22:36 --> Query error: Incorrect integer value: '' for column 'visitor_1_dl_number' at row 1 - Invalid query: INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`, `is_unavailable`, `id_users_provider`, `id_services`, `id_inmate`, `visitor_2_name`, `visitor_3_name`, `visitor_4_name`, `visitor_1_dl_number`, `visitor_2_dl_number`, `visitor_3_dl_number`, `visitor_4_dl_number`, `visitor_1_dl_state`, `visitor_2_dl_state`, `visitor_3_dl_state`, `visitor_4_dl_state`, `visitor_1_dl`, `visitor_2_dl`, `visitor_3_dl`, `visitor_4_dl`, `location`, `id_users_customer`, `book_datetime`, `hash`) VALUES ('2021-08-31 17:00:00', '2021-08-31 17:20:00', '', 0, '4', '1', '0', '', '', '', '', '', '', '', 'Texas', 'Select', 'Select', 'Select', 'C:\\fakepath\\image.png', '', '', '', 'Room 1', '13', '2021-08-30 22:22:36', '863935233eea7adc0644844f57af5475')
ERROR - 2021-08-30 22:22:49 --> Query error: Incorrect integer value: '' for column 'visitor_2_dl_number' at row 1 - Invalid query: INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`, `is_unavailable`, `id_users_provider`, `id_services`, `id_inmate`, `visitor_2_name`, `visitor_3_name`, `visitor_4_name`, `visitor_1_dl_number`, `visitor_2_dl_number`, `visitor_3_dl_number`, `visitor_4_dl_number`, `visitor_1_dl_state`, `visitor_2_dl_state`, `visitor_3_dl_state`, `visitor_4_dl_state`, `visitor_1_dl`, `visitor_2_dl`, `visitor_3_dl`, `visitor_4_dl`, `location`, `id_users_customer`, `book_datetime`, `hash`) VALUES ('2021-08-31 17:00:00', '2021-08-31 17:20:00', '', 0, '4', '1', '0', '', '', '', '1', '', '', '', 'Texas', 'Select', 'Select', 'Select', 'C:\\fakepath\\image.png', '', '', '', 'Room 1', '13', '2021-08-30 22:22:49', 'd0027e20c3892d3e5fb317c4249a0132')
ERROR - 2021-08-30 22:22:59 --> Query error: Field 'new_test_field' doesn't have a default value - Invalid query: INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`, `is_unavailable`, `id_users_provider`, `id_services`, `id_inmate`, `visitor_2_name`, `visitor_3_name`, `visitor_4_name`, `visitor_1_dl_number`, `visitor_2_dl_number`, `visitor_3_dl_number`, `visitor_4_dl_number`, `visitor_1_dl_state`, `visitor_2_dl_state`, `visitor_3_dl_state`, `visitor_4_dl_state`, `visitor_1_dl`, `visitor_2_dl`, `visitor_3_dl`, `visitor_4_dl`, `location`, `id_users_customer`, `book_datetime`, `hash`) VALUES ('2021-08-31 17:00:00', '2021-08-31 17:20:00', '', 0, '4', '1', '0', '', '', '', '1', '1', '1', '1', 'Texas', 'Select', 'Select', 'Select', 'C:\\fakepath\\image.png', '', '', '', 'Room 1', '13', '2021-08-30 22:22:59', 'd767cedc08b3cde136fabb1984c6cf2f')
ERROR - 2021-08-30 22:25:54 --> Query error: Field 'new_test_field' doesn't have a default value - Invalid query: INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`, `is_unavailable`, `id_users_provider`, `id_services`, `id_inmate`, `visitor_2_name`, `visitor_3_name`, `visitor_4_name`, `visitor_1_dl_number`, `visitor_2_dl_number`, `visitor_3_dl_number`, `visitor_4_dl_number`, `visitor_1_dl_state`, `visitor_2_dl_state`, `visitor_3_dl_state`, `visitor_4_dl_state`, `visitor_1_dl`, `visitor_2_dl`, `visitor_3_dl`, `visitor_4_dl`, `location`, `id_users_customer`, `book_datetime`, `hash`) VALUES ('2021-08-31 17:00:00', '2021-08-31 17:20:00', '', 0, '2', '1', '0', '', '', '', '1', '1', '1', '1', 'Texas', 'Select', 'Select', 'Select', 'C:\\fakepath\\image.png', '', '', '', 'Room 1', '13', '2021-08-30 22:25:54', '7a9c6e83f3745cef2f3d92f779184c77')
ERROR - 2021-08-30 22:29:51 --> Query error: Field 'new_test_field' doesn't have a default value - Invalid query: INSERT INTO `ea_appointments` (`start_datetime`, `end_datetime`, `notes`, `is_unavailable`, `id_users_provider`, `id_services`, `id_inmate`, `visitor_2_name`, `visitor_3_name`, `visitor_4_name`, `visitor_1_dl_number`, `visitor_2_dl_number`, `visitor_3_dl_number`, `visitor_4_dl_number`, `visitor_1_dl_state`, `visitor_2_dl_state`, `visitor_3_dl_state`, `visitor_4_dl_state`, `visitor_1_dl`, `visitor_2_dl`, `visitor_3_dl`, `visitor_4_dl`, `location`, `id_users_customer`, `book_datetime`, `hash`) VALUES ('2021-08-31 17:00:00', '2021-08-31 17:20:00', '', 0, '2', '1', '0', '', '', '', '1', '1', '1', '1', 'Texas', 'Select', 'Select', 'Select', 'C:\\fakepath\\image.png', '', '', '', 'Room 1', '13', '2021-08-30 22:29:51', '6c67c73dd00aa6c28120d8b9b4efbea1')
ERROR - 2021-08-30 23:00:41 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): No such file or directory /Users/peterswanson/Sites/localhost/EA/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2021-08-30 23:00:41 --> Unable to connect to the database
ERROR - 2021-08-30 23:40:21 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): No such file or directory /Users/peterswanson/Sites/localhost/EA/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2021-08-30 23:40:21 --> Unable to connect to the database
